version: "3"
services:
  app:
    container_name: fastify-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-fastify-api
    image: mongo
    ports:
      - "27018:27017"